name: Selenide Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make Gradle Wrapper executable
        run: chmod +x gradlew
        
      - name: Build Project
        run: ./gradlew assemble testClasses

        ## Excludes the logs from pulling images
      - name: Run Selenide Tests
        run: ./gradlew test 2>&1 | grep -vE '\[docker-java-stream-(416180839|-1729979775)\]'

